### ISSUE TITLE
Crash with inserter...

### ISSUE THREAD

**Issue by tecnicocorrea** [cout970/Magneticraft-API-and-Issues#36]
Other report... please the mod its wonderfoul!!! 

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 14/10/15 20:49
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at com.cout970.magneticraft.tileentity.TileInserter.checkFilter(TileInserter.java:369)
	at com.cout970.magneticraft.tileentity.TileInserter.canExtract(TileInserter.java:331)
	at com.cout970.magneticraft.tileentity.TileInserter.extractFromBelt(TileInserter.java:281)
	at com.cout970.magneticraft.tileentity.TileInserter.suckFromBelt(TileInserter.java:272)
	at com.cout970.magneticraft.tileentity.TileInserter.func_145845_h(TileInserter.java:106)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.cout970.magneticraft.tileentity.TileInserter.checkFilter(TileInserter.java:369)
	at com.cout970.magneticraft.tileentity.TileInserter.canExtract(TileInserter.java:331)
	at com.cout970.magneticraft.tileentity.TileInserter.extractFromBelt(TileInserter.java:281)
	at com.cout970.magneticraft.tileentity.TileInserter.suckFromBelt(TileInserter.java:272)
	at com.cout970.magneticraft.tileentity.TileInserter.func_145845_h(TileInserter.java:106)

-- Block entity being ticked --
Details:
	Name: com.cout970.magneticraft.tileentity.TileInserter_Mg // com.cout970.magneticraft.tileentity.TileInserter
	Block type: ID #428 (inserter // com.cout970.magneticraft.block.BlockInserter)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-179,64,-72), Chunk: (at 13,4,8 in -12,-5; contains blocks -192,0,-80 to -177,255,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #428 (inserter // com.cout970.magneticraft.block.BlockInserter)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: INGENIERÍA
	All players: 1 total; [EntityPlayerMP['warlock'/1000770, l='INGENIERÍA', x=-176,30, y=64,00, z=-70,89]]
	Chunk stats: ServerChunkCache: 401 Drop: 0
	Level seed: -826740750576260258
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 2;7,59x1,3x3,2;1;village,biome_1,decoration,stronghold,mineshaft,lake,lava_lake,dungeon
	Level spawn location: World: (-195,4,45), Chunk: (at 13,0,13 in -13,2; contains blocks -208,0,32 to -193,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 488432 game time, 14616 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 37880 (now: false), thunder time: 45270 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 167398816 bytes (159 MB) / 487813120 bytes (465 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1517 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1517-1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAA	Forge{10.13.4.1517} [Minecraft Forge] (forge-1.7.10-10.13.4.1517-1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAA	Enchiridion{1.1} [Enchiridion] (Enchiridion-1.7.X-1.2b.jar) 
	UCHIJAAAAAAAAAAAAAA	AgriCraft{1.7.10-1.3.1} [AgriCraft] (AgriCraft-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAA	craftguide{1.6.8.1} [CraftGuide] (CraftGuide-Mod-1.7.10.zip) 
	UCHIJAAAAAAAAAAAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAAAAAAAAAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAAAAAAAAAAAA	Magneticraft{0.5.1} [Magneticraft] (magneticraft-0.5.1.zip) 
	UCHIJAAAAAAAAAAAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['warlock'/1000770, l='INGENIERÍA', x=-176,30, y=64,00, z=-70,89]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Cypher121** [comment]
Same as #31
