### ISSUE TITLE
Shelves with Thermal Dynamics ducts

### ISSUE THREAD

**Issue by mainframecn** [cout970/Magneticraft-API-and-Issues#77]
**Issue:**
Deleted items / corrupted world when shelves contain less than full stack of ducts from thermal dynamics.

**Crashlog:**
java.lang.NullPointerException: Unexpected error
	at com.cout970.magneticraft.tileentity.shelf.TileShelf.getInventory(TileShelf.java:20)
	at com.cout970.magneticraft.tileentity.shelf.TileShelf.getRealSize(TileShelf.java:48)
	at com.cout970.magneticraft.tileentity.shelf.TileShelf.func_70302_i_(TileShelf.java:40)
	at cofh.thermaldynamics.duct.item.TileItemDuct.isSignificantTile(TileItemDuct.java:177)
	at cofh.thermaldynamics.block.TileTDBase.handleTileSideUpdate([LP|ASM] TileTDBase.java:429)
	at cofh.thermaldynamics.block.TileTDBase.handleSideUpdate([LP|ASM] TileTDBase.java:369)
	at cofh.thermaldynamics.block.TileTDBase.onNeighborTileChange([LP|ASM] TileTDBase.java:520)
	at cofh.core.block.BlockCoFHBase.onNeighborChange(BlockCoFHBase.java:195)
	at net.minecraft.world.World.func_147453_f(World.java:3875)
.....etc

**Comment by Cypher121** [comment]
When does it occur? Does it only happen with ducts and not with hoppers/inserters/other pipes? Does it happen with every block of the unit or only with specific blocks?

**Comment by mainframecn** [comment]
It deletes the entire stack of ducts after a restart of the world. It has also done this with the brass casting plates (single items).
I haven't notice any other issues so far.

**Comment by mainframecn** [comment]
Connecting thermal dynamics pipes to shelves seem to corrupt the world save.

**Comment by mainframecn** [comment]
Shelves have also deleted items from AE2 rv3. It has deleted the iron plates for the inscriber.

**Comment by MechWarrior99** [comment]
Sorry I don't know what is causing the problem for you. I have been unable to reproduce this bug in any way.

**Comment by DeathStapler** [comment]
As you can see from issue #82, I have seen this problem.  I see it every time that I place a shelving unit next to an existing Mekanism Logistical Transport pipe.  I also tested it with Itemducts from Thermal Expansion.  In both cases it results in a crash.

I was going to attempt to debug the problem, but I'm not sure how to setup IntelliJ to work with mod packs.
